"""initial schema

Revision ID: 144ec264aabb
Revises: 
Create Date: 2026-06-11 15:41:45.386308
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '144ec264aabb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('reseller_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orgs'))
    )
    op.create_table('platform_staff',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_staff')),
    sa.UniqueConstraint('email', name=op.f('uq_platform_staff_email'))
    )
    op.create_table('stores',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_stores_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores'))
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_org_id'), ['org_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('store_id', sa.String(length=32), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_devices_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_devices_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_api_key_hash'), ['api_key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_store_id'), ['store_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('store_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_users_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_users_store_id_stores'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('org_id', 'email', name='uq_user_org_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('cameras',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('fov_h_deg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_cameras_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_device_id'), ['device_id'], unique=False)

    op.create_table('heartbeats',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('sent_at', sa.Float(), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('camera_ok', sa.Boolean(), nullable=False),
    sa.Column('fps_display', sa.Float(), nullable=False),
    sa.Column('fps_analysis', sa.Float(), nullable=False),
    sa.Column('people_tracked', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_heartbeats_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_heartbeats_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heartbeats'))
    )
    with op.batch_alter_table('heartbeats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heartbeats_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_heartbeats_org_id'), ['org_id'], unique=False)

    op.create_table('metric_buckets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('store_id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.String(length=40), nullable=False),
    sa.Column('window_end', sa.String(length=40), nullable=False),
    sa.Column('passersby', sa.Integer(), nullable=False),
    sa.Column('engaged', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('total_attention_s', sa.Float(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_metric_buckets_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_metric_buckets_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_metric_buckets_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_buckets')),
    sa.UniqueConstraint('device_id', 'window_start', name='uq_bucket_device_window')
    )
    with op.batch_alter_table('metric_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_buckets_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_buckets_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_buckets_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_buckets_store_id'))
        batch_op.drop_index(batch_op.f('ix_metric_buckets_org_id'))
        batch_op.drop_index(batch_op.f('ix_metric_buckets_device_id'))

    op.drop_table('metric_buckets')
    with op.batch_alter_table('heartbeats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heartbeats_org_id'))
        batch_op.drop_index(batch_op.f('ix_heartbeats_device_id'))

    op.drop_table('heartbeats')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_device_id'))

    op.drop_table('cameras')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))

    op.drop_table('users')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_store_id'))
        batch_op.drop_index(batch_op.f('ix_devices_org_id'))
        batch_op.drop_index(batch_op.f('ix_devices_api_key_hash'))

    op.drop_table('devices')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_org_id'))

    op.drop_table('stores')
    op.drop_table('platform_staff')
    op.drop_table('orgs')
    # ### end Alembic commands ###
